### ISSUE TITLE
NFT deposit to Soonaverse conflicting

### ISSUE THREAD

**Issue by Machstemal** [soonaverse/soonaverse-dao#1119]
Hello,
I have a problem with an NFT deposit to Soonaverse, I don't really know if it's a bug. In the Soonaverse Discord I opened a ticket to which I was replied that I should report it in Github.

I bought the NFT in the Soonaverse. https://soonaverse.com/space/0xac650dd2474937356d4934f4f6bca4d4f0a0337b
"SPEC OG" space.

I withdrew it on April 13th and transferred it to my wallet Tanglepay and then forwarded it to one of my FF wallets. So far everything was ok.

Then on April 14th I tried to deposit it back into another account of mine at Soonaverse.
Something went wrong and the NFT is "in progress" in the transaction list.
UID: 0x00cd269bf18e9dbfb564a1ea9ce15b844ee608b2, Attempts: 6

I've done the same process with about 25 other NFTs from Space "Tangle Collectibles" and had no problems.

For the conflicting transaction I have a link to Shimmer Explorer: https://explorer.shimmer.network/shimmer/block/0x65b7919fda6c349997e7e4c6309b6ba0d94b0d96778d946aab2de355a4faeaa4?tab=Payload.

I don't know if I can do anything at all without help. I only understand that there is a conflict in the transaction, but I don't know how to solve it.
I was asked in the discord if I paid the storage deposit. I checked the Firefly and I think I paid the deposit. I'm not quite sure.
I have a few screenshots of the transaction as it is now displayed in the firefly.

**Screenshots**
![Screenshot 2023-04-18 212835](https://user-images.githubusercontent.com/96343106/232891304-5eeefee1-e285-4d36-ba96-5bf1b07c09ac.png)

![Screenshot 2023-04-18 212929](https://user-images.githubusercontent.com/96343106/232891659-9d5ed094-d37a-4a72-a563-fe6d820e5e16.png)

![Screenshot 2023-04-18 213019](https://user-images.githubusercontent.com/96343106/232891756-a0ab6f37-6119-4bc2-a501-207e03c6bd16.png)

**Desktop**
Windows 10 Home
Version 22H2
Installed on ‎04/12/2023
Operating system build 19045.2846
Performance Windows Feature Experience Pack 120.2212.4190.0

**Firefly**
Version 2.1.0
Language: en
Currency: undefined
Node list: https://api.shimmer.network
Platform: win32
Platform version: 10.0.19045
Platform architecture: x64
CPU count: 8
Total memory: 16332.3 MB
Free memory: 8556.8 MB

I hope someone can help here or tell me who to contact to solve the problem.
greeting
Machste

**Comment by Machstemal** [comment]
Sorry, forgot
Discord username: Machste[FI]#0189

Soonaverse 1. Username: @Meta Machste
Connected to Metamask: 0x74b61d8fAd7D42E0735F4395c7A3cAF2d18713ee

Soonaverse 2. Username: @Machste
Connected to Tanglepay: smr1qpxjfnw4gtp0w68knhs97uqe5ztpp7ddlz8eg22hk70uyc5lgkjpjewd2vj
I think this is needed as info.

**Comment by Machstemal** [comment]
Thanks Adam @adamunchained,
well I claimed the NFT from my transaction list and then got the storage deposit back to my SMR address. But the NFT is nowhere to be found.
On Soonavers, @Meta maske is displayed in my user profile
"You won an NFT ef
You are the proud owner of a new NFT. Congratulations!"
when i click on it i get this page.
https://soonaverse.com/nft/not-found
![Screenshot 2023-04-19 093526](https://user-images.githubusercontent.com/96343106/233002621-f3fefb56-66b6-4292-8d07-7a585eb38152.png)

I've searched all the Firefly wallets I have. The NFT cannot be found.
What now?
Do I have to wait for the fix in the upcoming release or did something go wrong again?

Greeting Machste

**Comment by adamunchained** [comment]
@Machstemal - NFT should be back in your Firefly. It didn't go there? Can you provide transaction reference (block on Shimmer) for your storage deposit refund please?

**Comment by theflyingrabbit** [comment]
@Machstemal Sorry for the confusion, I have managed to identify the problem, the fix will be released later today. Once done you will be able to claim the nft again.

**Comment by Machstemal** [comment]
@theflyingrabbit  hey thanks
I'm patient and excited at the same time :)

**Comment by adamunchained** [comment]
We've just released new version, please try again.

**Comment by Machstemal** [comment]
@adamunchained Unfortunately I still can't claim the NFT or I don't understand how to do it. No claim option was displayed in the transaction list for the relevant NFT. Would Soonaverse or one of you have to make this possible or should it just happen by itself?

**Comment by adamunchained** [comment]
@Machstemal - Can you see the option now? Sorry we forgot to revert your transaction back into claimable position.

You should see this:
<img width="963" alt="Screenshot 2023-04-20 at 7 16 33 AM" src="https://user-images.githubusercontent.com/130610/233394381-5a956dc0-38c0-4ca6-8618-dabb9a1207c8.png">

**Comment by Machstemal** [comment]
Tata, ef is back!!!
Thank you guys,
This is the true power of the Tangle and the people who built it :)

![image](https://user-images.githubusercontent.com/96343106/233531843-f47e2ae9-62bd-47af-8759-dabe6ba86727.png)


Has now worked really well with deep link and, as always, really super fast.
By the way, also a great idea with the Soonaverse pfp as NFT. Thought it was a joke, at first, but it's actually a feature of the update.
Good idea

thanks again
Greeting Machste

**Comment by adamunchained** [comment]
Awesome, glad to hear it's finally working!

**Comment by Machstemal** [comment]
One more question, can I send ef on a trip again now?
Where was the error, was it me or a bug?
I don't want to make the same mistake twice ;)

**Comment by theflyingrabbit** [comment]
It was an internal error, it is fixed now. You can safely send ef on a drip again, but do it without storage deposit lock.
